# MySQL JDBC connection
spring.datasource.url=jdbc:mysql://localhost:3306/jayalakshmi
spring.datasource.username=root
spring.datasource.password=Gayam@12
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate and JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
